### ISSUE TITLE
Addition of Incident Priority

### ISSUE THREAD

**Issue by simonsigre** [PagerDuty/pdagent#115]
Is there any word on when the new Incident Priority option will be available for pdagent so we can;

`pd-send` -k "xxxxxxxxx" -t trigger -d "Server is on fire" -i server.fire -p "P1"

**Comment by simonsigre** [comment]
Just realised this is a V2 feature at currently the app is V1

**Comment by Deconstrained** [comment]
Hi @simonsigre , 

It is not yet possible through either version of the Events API to set the incident priority label, and PagerDuty Agent is an Events client. However, it is possible to set the alert severity level in the V2 Events API, or through the v1 Events API with event rules. It may yet be possible in the future of PagerDuty to set incident priority based on alert / event severity.

Since setting the incident priority via the Events API is a prerequisite of being able to set the incident priority with PagerDuty agent, the agent cannot yet be updated to set incident priority.
