### ISSUE TITLE
Add Flags for All PD-CEF Fields (Events API v2)

### ISSUE THREAD

**Issue by aaron-goulet-bfg** [PagerDuty/pdagent#127]
There is currently no way to pass several fields present in the [PagerDuty Common Event Format (PD-CEF)](https://v2.developer.pagerduty.com/docs/events-api-v2#pagerduty-common-event-format-pd-cef), most notably `Severity`, `Component`, `Group`, and `Class`.  These fields are potentially very useful in certain deployment strategies, so it would be ideal to see them supported.

**Comment by apollo13** [comment]
@dobs Is there any rough ETA on Events API v2 support?

**Comment by dobs** [comment]
Hi @apollo13, and sorry for the delay responding -- no firm ETA at the moment but I'll be taking a look at this in coming weeks.

**Comment by ChezCrawford** [comment]
After yet another log delay here, we have added this support into our new agent: [PagerDuty/go-pdagent](https://github.com/PagerDuty/go-pdagent).  

@aaron-goulet-bfg @apollo13 any chance you all could have a look at this and see if it meets your needs?

**Comment by apollo13** [comment]
Oh lol, I already gave up any hope. But yes @ChezCrawford did looks as if it were to satisfy our needs. Thanks for working on it!

**Comment by nekodojo** [comment]
> > After yet another log delay here, we have added this support into our new agent: [PagerDuty/go-pdagent](https://github.com/PagerDuty/go-pdagent).
> > @aaron-goulet-bfg @apollo13 any chance you all could have a look at this and see if it meets your needs?

Since this got closed 3 years ago, should we assume that "go-pdagent" is the better agent and this older pdagent will stop getting updates?  

I can see on Pagerduty Developer site that pdagent is still listed as the "official" agent, but a footnote says "go-pdagent *This project originated inside of PagerDuty with the eventual goal of replacing the Python based pdagent."

So what are the next steps by PD dev team to promote go-pdagent and retire Python based pdagent?  Is this still the plan? 


> go-pdagent is still in **beta** and does not support all event api v2 fields ([PagerDuty/go-pdagent#34](https://github.com/PagerDuty/go-pdagent/issues/34))

Good point... I'm hesitant to switch over to go-pdagent since it looks like it has open issues for 2+ years that aren't getting worked on. At least it supports some PD-CEF fields but I guess not all of them?

Anyway, my concern is that PD team is closing bugs against the older pdagent with comments pointing to the new one, but the new one is also not getting any love.

**Comment by apollo13** [comment]
I'd say that at this point it is fair to say that both agents basically seem unmaintained completely.
