### ISSUE TITLE
Cannot install on Ubuntu 16.04

### ISSUE THREAD

**Issue by mdcollins05** [PagerDuty/pdagent#98]
In Ubuntu 16.04 PDAgent won't install via apt-get because it depends on the python-support package. The package has been removed from this version.

16.04 still has python 2.7 support, so installing python 2.7 and git cloning works, it just doesn't have all the binaries in the right place and no init script.

**Comment by kenrose** [comment]
Filed EM-675 to internally track this.

**Comment by fninja** [comment]
@kenrose @astoltz hello :)
is there any progress here?
i.e. at what part of the offical integration howTo for Check_MK do we need to branch off and to manual work?
which binary goes where and do you need help writing a systemd service file?

**Comment by cncook001** [comment]
5+ months to release an update.  Yes.  Pager Duty engineering needs help :)

**Comment by astoltz** [comment]
I'm just some guy. I've been running the agent for a few months now on Ubuntu 16.04 with no issue. I've been using the existing init.d script. I'm not sure how the PagerDuty team manages their releases so I haven't had much to contribute. They'll need two separate distributions (Ubuntu 16.04 and 14.04) since 14.04 doesn't have systemd support. The current setup only does a single build at this time. I can certainly assist, if needed.

**Comment by mlewis033** [comment]
Fixed with #100
